# Site settings
title: Dietrich Ayala
email: autonome@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Working on Firefox OS so the next two billion people to come online have
  freedom and choice.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://autonome.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
